# Generated by Django 4.1.1 on 2022-10-18 02:16

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "uptaded",
                    models.DateField(auto_now=True, verbose_name="Data de atualização"),
                ),
                ("username", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.contrib.auth.password_validation.validate_password
                        ],
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="O número de telefone deve ser inserido no formato '0412 345 678', '+61412345678', '+5581912345678', '+55 81 91234-5678', '+61 0412-345-678', '0412345678'. Dígitos permitidos de 8 Até 24.",
                                regex="(?:\\+\\d{2})?\\d{3,4}\\D?\\d{3}\\D?\\d{3}",
                            )
                        ],
                    ),
                ),
                ("birthday", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
